### ISSUE TITLE
Windows Installer

### ISSUE THREAD

**Issue by Gnarmagon** [PR4GM4/kit-kat#22]
**A little Windows Installer:**
[Dropbox Folder with Checksumms](https://www.dropbox.com/sh/u7mzj0z9q3wg3md/AABOMsVlfLAW9ju9r1cfXS-xa?dl=0)
[Virus Total Scan](https://www.virustotal.com/de/file/d0ca88af6810ce053669da476feecb1dd178c2cfef0d1db79cd8da58661c085a/analysis/1488710606/)

Hopefully you don't blame me for creating an Issue but I had no permissions to Upload it directly in the Repository :(

Have a nice Day !

Lucas

**Comment by initPRAGMA** [comment]
I dont really understand why you made an "Installer" for it, all you need to do to make it as if it was installed is to move it into a folder in Program Files, and then create a shorcut for it to desktop. Done.

But k
