### ISSUE TITLE
Closing program 

### ISSUE THREAD

**Issue by vipertongn** [PR4GM4/kit-kat#24]
hello, i found that say if I wanted to stop streaming the 3ds onto my laptop, closing NTR causes a disconnect from my ps4 controller.  Same thing happens if I were to close KitKat and reopen it at a later time.  I'm forced to restart my computer before it can re-establish connection.  Is there a specific process in closing the program without hanging up the connection between 3ds and controller when I reopen the app?

**Comment by PR4GM4** [comment]
kit-kat does the controller stuff, so closing it will obviously disconnect it.
