### ISSUE TITLE
Black screen/frozen screen

### ISSUE THREAD

**Issue by BrandyKoopa** [PR4GM4/kit-kat#25]
evrytime i start a new pokemon game ( be it X/Y , ORAS , Sun/Moon) evrytime i pass the intro and get into the game i get a black screen but i still hear the audio i even tried your method  but it still freezes help :(

**Comment by PR4GM4** [comment]
1. Open NTR 3.6,
2. Hold down L+DPADDOWN+SELECT, "Debugger Options..." -> "Enable debugger".
3. Connect via kit-kat
4. Open the Game.
