### ISSUE TITLE
Retrying to Connect After Custom Time and/or Connect Shortcut

### ISSUE THREAD

**Issue by Saphiresurf** [PR4GM4/kit-kat#27]
Hey! I was curious, have you considered implementing a feature where you can setup kit-kat to retry connecting again every [custom amount] of seconds/minutes?

Mostly wondering about this because it would make it a lot easier to have dedicated hardware hooked up to a TV so that you can just run NTR from your 3DS to connect without having to worry about the pressing the connect button in kitkat.

Alternatively do you think there could just be a shortcut to "Connect" and to send a ram patch from Kit Kat so perhaps I could just have an easily accessible keyboard out that I press the shortcut on when I want to connect my 3DS to the laptop/desktop plugged into my TV?

Thanks for considering!

**Comment by PR4GM4** [comment]
For the mempatch:
1. Open NTR 3.6,
2. Hold down L+DPADDOWN+SELECT, "Debugger Options..." -> "Enable debugger".
3. Connect via kit-kat
4. Open the Game.

But for retrying and stuff I dont have plans on that atm no.
