### ISSUE TITLE
11.4 system is not compatible

### ISSUE THREAD

**Issue by lvziho** [PR4GM4/kit-kat#29]
11.4 system should not be compatible with the problem of NTRViewer 11.4 system will be open when the white screen does not show

**Comment by lvziho** [comment]
11.4 system should not be compatible with the problem of NTRViewer 11.4 system will be open when the white screen does not show

**Comment by PR4GM4** [comment]
Try on the new version of NTR, look at the new tutorial on gbatemp on my thread.
