### ISSUE TITLE
11.4, NTR Streaming is broken.

### ISSUE THREAD

**Issue by Juto851** [PR4GM4/kit-kat#30]
11.4, NTR Streaming is broken. white screen when I connect my n3DS

**Comment by eaglejs** [comment]
I believe this is something to do with updating to the latest 3DS Software 11.4.x For this, NTR Streaming is broken. I don't think ititPRAGMA works on that bit, so all we can do is wait for a fix or downgrade back to 11.3.x :)

**Comment by wrathsoffire76** [comment]
NTR has been updated BTW

**Comment by PR4GM4** [comment]
White screen means connection issues, nothing to do with NTR or kit-kat.
