### ISSUE TITLE
New Code to patch online services for Sun and Moon...etc.

### ISSUE THREAD

**Issue by YeraySL** [PR4GM4/kit-kat#31]
[https://pbs.twimg.com/media/C_m4JhIWAAAZZLx.jpg](url)

**Comment by PR4GM4** [comment]
1. Open NTR 3.6,
2. Hold down L+DPADDOWN+SELECT, "Debugger Options..." -> "Enable debugger".
3. Connect via kit-kat
4. Open the Game.
