### ISSUE TITLE
Kit-kat won't open at all

### ISSUE THREAD

**Issue by randomination** [PR4GM4/kit-kat#33]
I try to open the exe file but tbe process closes itself after a few seconds

**Comment by PR4GM4** [comment]
Ill need more information then that. Sorry dude.

**Comment by shakkar23** [comment]
same :/ except mine doesn't pop up at all. The cursor will show something is loading but nothing pops up.

**Comment by PR4GM4** [comment]
This is an ancient ticket dude.
