### ISSUE TITLE
Memory Patch not being applied correctly to Pokemon ORAS

### ISSUE THREAD

**Issue by MarcTowler** [PR4GM4/kit-kat#35]
Hey there,

I have been using Kit-Kat for a while and recently I was required to update NTR and the system so NTR now does not have a 3.4 option, it only gives me 3.2, 3.3 and 3.5. When using 3.5, Kit-Kat is able to connect to my 3ds with no issues, NTR Viewer opens up fine and I can move around. Both with and without a memory patch (apparently) being successfully applied, all I get inside Pokemon ORAS is a black screen on NTR Viewer, no error messages

**Comment by MarcTowler** [comment]
any ideas?

**Comment by PR4GM4** [comment]
1. Open NTR 3.6,
2. Hold down L+DPADDOWN+SELECT, "Debugger Options..." -> "Enable debugger".
3. Connect via kit-kat
4. Open the Game.
