### ISSUE TITLE
kit kat has an error

### ISSUE THREAD

**Issue by starrkaleb** [PR4GM4/kit-kat#36]
when i click on kit-kat.exe it says this," Please re-download kit-kat manually as an Update Bug Occured! Error: The remote server returned an error: (404) Not Found." It still opens but when i try to do livestreams it keeps turning the stream on and off again. My bootntr doesnt have 3.4 all it has is 3.2, 3.3, and 3.5. It still connects and my FBI is at 2.4.8. Can you please help me.

**Comment by TheNain38** [comment]
It's fixed in the latest commit: https://github.com/initPRAGMA/kit-kat/commit/51a3926811b35b62795bc41142430ee018010bea

**Comment by starrkaleb** [comment]
what do i do

**Comment by TheNain38** [comment]
You need to wait for initPRAGMA to do a new release, OR you compile the code yourself

**Comment by starrkaleb** [comment]
ok so how do compile the code

**Comment by TheNain38** [comment]
I'd like to upload an already compiled file, but... github is bugged --'

**Comment by starrkaleb** [comment]
oh ok

**Comment by TheNain38** [comment]
I'm uploading it to Mega right now

**Comment by TheNain38** [comment]
Here you go: https://mega.nz/#!ILYSEYKD!U7PXRkWGiGC-CLzCSBlIMDXRsbio6iisGXvnD6auDiU

**Comment by TheNain38** [comment]
@starrkaleb Please close the issue...

**Comment by emilie777** [comment]
I'm having the same issue. I tried using the download you provided but still getting the white screen. It took away the error though. I disabled my antivirus and firewall :S would there be any other reason why there's still a white screen?

**Comment by PR4GM4** [comment]
New version released. Try on that.
