### ISSUE TITLE
i found a similar kit kat app 3ds for the O3DS

### ISSUE THREAD

**Issue by Orionsilver** [PR4GM4/kit-kat#41]
it works with O3DS 
lagging

older games below 2016 
Pokemon Sun and Moon with get a stuck screen 
[HorizonM-master.zip](https://github.com/PR4GM4/kit-kat/files/1266346/HorizonM-master.zip)

**Comment by Orionsilver** [comment]
i included the exe file in the master folder

**Comment by Orionsilver** [comment]
SDL2.dll is in the Folder
Put the SDL2.dll in System32 to work

**Comment by Orionsilver** [comment]
https://www.youtube.com/watch?v=rPZeI-MMmIk

https://www.youtube.com/watch?v=ROO__HtmBMo

**Comment by PR4GM4** [comment]
Its not mine so I dont give support for it, sorry man.
