### ISSUE TITLE
Update Error!

### ISSUE THREAD

**Issue by emilie777** [PR4GM4/kit-kat#43]
"Please re-download kit-kat manually as an Updating Bug Occurred! Error: The remote server returned an error: (404) Not Found."

That error popped up when I tried to run kit-kat for screen capture. I'm using the latest release running the Boot NTR on 3.6 (3.4 isn't available and I tried all the other ones and they won't work). It seems to boot correctly from my Nintendo New 3DS XL, but the PC side of it doesn't seem to be working and I assume because of that error. I tried to run it anyways to see if it would work and it says it's connected but it's just showing a white screen. I followed the instructions disabling my antivirus and made kit-kat as an exception through my firewall but still no luck. If anyone could help me out with this I'd so greatly appreciate it. I really want to start streaming games. :(

**Comment by cinnacutie** [comment]
The same thing is happening to me right now :/

**Comment by Zetawilk** [comment]
Ibid.

**Comment by MattyMetroid** [comment]
im getting the same error :/ worked fine once

**Comment by PR4GM4** [comment]
Update with the newly released .exe in Releases. Auto-updater was removed.
