### ISSUE TITLE
Pokemon USUM Support

### ISSUE THREAD

**Issue by EsteeMcCrawly** [PR4GM4/kit-kat#44]
The software doesn't recognize the need to write an NFC patch for at least Pokemon Ultra Moon, making it impossible to record while playing the story.

**Comment by PR4GM4** [comment]
1. Open NTR 3.6,
2. Hold down L+DPADDOWN+SELECT, "Debugger Options..." -> "Enable debugger".
3. Connect via kit-kat
4. Open the Game.
