### ISSUE TITLE
POKEMON ULTRA SUN & MOON SUPPORT

### ISSUE THREAD

**Issue by salazzledazzle** [PR4GM4/kit-kat#45]
kit kat refuses to write a patch for US/UM making it virtually impossible to stream the story :( please help ASAP i wanna do lets plays on my youtube channel!!!!! please reply with a fix ASAP i just bought US/UM today and nothing is working

**Comment by PR4GM4** [comment]
1. Open NTR 3.6,
2. Hold down L+DPADDOWN+SELECT, "Debugger Options..." -> "Enable debugger".
3. Connect via kit-kat
4. Open the Game.
