### ISSUE TITLE
Pokemon VC Discoloration

### ISSUE THREAD

**Issue by PyroBeast** [PR4GM4/kit-kat#47]
![3ds vc filter](https://user-images.githubusercontent.com/9810695/36189853-58657d28-111a-11e8-98ca-9ac008a12f9f.PNG)

![3ds_vc_on_console](https://user-images.githubusercontent.com/9810695/36189891-8fad6f3e-111a-11e8-8d64-893f7b150e95.png)

Title states. The first one appears to have an odd filter of sorts when streamed but the next is what appears on the console. Any ideas?

**Comment by PR4GM4** [comment]
It seems to be a Boot NTR bug with the filter system, seems the default/off one has still somewhat of a filter. Its nothing to do with kit-kat/ntr-viewer.
