### ISSUE TITLE
kit-kat.exe wont open

### ISSUE THREAD

**Issue by shakkar23** [PR4GM4/kit-kat#49]
Kit-kat wont open and it doesn't load either, the cursor shows something is loading but nothing pops up.
Latest .net framework, windows 10 update, and latest .net core. the ui works but doesn't connect either.

**Comment by PR4GM4** [comment]
try install .net 4.6.2 and C++ 2013 x86 (MUST REBOOT! IMPORTANT)

**Comment by shakkar23** [comment]
will .net 4.7.1 work?

**Comment by PR4GM4** [comment]
Yeah

**Comment by shakkar23** [comment]
it pops up thnx!

**Comment by shakkar23** [comment]
mode 3 is for O3ds right?

**Comment by shakkar23** [comment]
how do i make sure that malware protection isnt the one causing the failures?

**Comment by PR4GM4** [comment]
Pretty sure it was missing C++ 2013 x86 that was causing it and not .Net.
o3DS isnt supported. They just arent powerful enough.

**Comment by shakkar23** [comment]
:( now when i connect with my 3ds it gets the wrong port number.

**Comment by PR4GM4** [comment]
Port number for FBI stuff etc is 5000, its nothing to do with NTR.
