### ISSUE TITLE
rar files currupt

### ISSUE THREAD

**Issue by k20stitch** [PR4GM4/kit-kat#50]
Both the 2.0 and follow up release are corrupt. Were they transferred in binary?

**Comment by PR4GM4** [comment]
Working fine for me m8

**Comment by k20stitch** [comment]
Tried from two different windows PCs

**Comment by PR4GM4** [comment]
Idk what to tell you my dude.
its an issue with your internet or something downloading failing somewhere.
Working perfectly fine on my end.
https://i.imgur.com/PgutSkE.png
